### PR TITLE
update to not duplicate persistent tags

### PR DESCRIPTION
**Pull request by thedavidthomas**
The getTagsToRemove ignores Persistent tags (which is expected) but the getTagsToAdd was not doing the same causing duplicate persistent tags. 

this PR performs the same check to prevent addTags from adding the persistent tags again.

### CODE REVIEW

**Comment by daun** [comment]
What's the intended use case here? What kind of duplicate tags are you seeing?

The persisting tags feature was added mainly to keep any stylesheets added dynamically by libraries like Google Maps so there was no need to apply this to new tags as well. Your change would have the opposite effect, basically preventing stylesheets of the new page from being added.

Maybe a duplicate check would make more sense here, like comparing `outerHTML`?

**Comment by thedavidthomas** [comment]
Currently we have a data attribute `data-persist` using the config 
```
new SwupHeadPlugin({
        persistTags: "*[data-persist]",
}),
```

this is on link, style and script tags in the `<head>` (critical styles e.t.c) that we know are not changing and don't want to remove and then re-add them again. The tags are on both the outgoing and incoming pages (just in the head not added dynamically by any libraries)

a compare or duplicate check would also work

**Comment by daun** [comment]
In that case, let's stick with the duplicate check. I just realized [we already have one](https://github.com/swup/head-plugin/blob/master/src/index.js#L115), that's probably why I've never seen duplicate tags. Maybe there's something going on on your site that prevents it from working?

**Comment by thedavidthomas** [comment]
I removed the persist attribute earlier today and can't see them duplicating anymore.
I don't remember exactly why we added them initially (it was a while ago)

it might have been to do with the non render-blocking link pattern we do
```
<link rel="stylesheet" href="/dist/css/page-frontpage.rest.css" media="print" onload="this.media='screen'; this.removeAttribute('onload');">
```

or something to do with Cloudflare Rocket Loader.

will do some further testing and report back.

**Comment by thedavidthomas** [comment]
it seems persist was added so the onload didn't cause a flash on transition

am testing out using `HTTP_X_REQUESTED_WITH` to send an already loaded style link if it's "swup"

**Comment by daun** [comment]
If you set persistTags to `link[rel=stylesheet]` and remove the `data-persist` attribute, it should keep the existing stylesheets around and add any new ones. There probably shouldn't be a flash but I'm not too familiar with the ramifications of non-blocking stylesheets.

**Comment by daun** [comment]
@thedavidthomas Does the above solution work?

**Comment by daun** [comment]
I'll close this for now as I can't reproduce the issue this is meant to solve. Please let us know if you found some other way to solve the problem at hand!

**Pull request closed without merging**
